parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\Integration\FootballApiClient:
    arguments:
      $footballApiKey: '%env(default::FOOTBALL_API_KEY)%'
      $footballApiBase: '%env(default::FOOTBALL_API_BASE)%'

  App\Service\Integration\IdfmClient:
    arguments:
      $idfmApiKey: '%env(default::IDFM_API_KEY)%'
      $idfmApiBase: '%env(default::IDFM_API_BASE)%'

  App\Service\Integration\SncfClient:
    arguments:
      $sncfApiToken: '%env(default::SNCF_API_TOKEN)%'
      $sncfApiBase: '%env(default::SNCF_API_BASE)%'

  App\Service\Integration\HomeAssistantClient:
    arguments:
      $homeAssistantUrl: '%env(default::HOME_ASSISTANT_URL)%'
      $homeAssistantToken: '%env(default::HOME_ASSISTANT_TOKEN)%'
